name: Build and Deploy to Dev
on:
  push:
    branches:
      - "feature/**"
jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Dev slot
        if: startsWith(github.ref, 'refs/heads/feature/')
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.WEBAPP_NAME }}
          slot-name: ${{ vars.SLOT_NAME }}
          images: "${{ vars.ACR_NAME }}.azurecr.io/${{  vars.IMAGE_NAME }}:${{ github.sha }}"
