name: Swap to Production
on:
  push:
    branches:
      - main
jobs:
  swap-to-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Swap Staging and Production
        if: github.ref == 'refs/heads/main'
        run: az webapp deployment slot swap -s ${{ vars.SLOT_NAME }} -n ${{ vars.WEBAPP_NAME }} -g ${{ vars.RESOURCE_GROUP }}
